vaultAuthRef: vault-auth

vaultSecretMount: mi-demovault

vaultSecretPath: "dev/db"

vaultRefreshAfter: 10s

vaultSecretType: kv-v1

# vaultRole: "7b7d4671-93ae-2ddd-7fbb-8fffa8164d4a"
# vaultRoleSecretName: vso-approle

# authType: approle

rolloutRestartTargets:
- kind: Deployment
  name: busybox
- kind: Deployment
  name: busybox2