apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: docker-secret
spec:
  vaultAuthRef: vault-auth
  mount: {{ .Values.vaultSecretMount }}
  path: dev/dockerconfig
  type: {{ .Values.vaultSecretType }}
  refreshAfter: {{ .Values.vaultRefreshAfter }}
  destination:
    name: demo-pull-secret
    create: true
    type: dockerconfigjson
    dockerConfig:
      username: ${username}
      password: ${password}
      registry: registry.example.com