apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: docker-secret
spec:
  vaultAuthRef: vault-auth
  mount: {{ .Values.vaultSecretMount }}
  path: dev/dockerconfig
  type: {{ .Values.vaultSecretType }}
  refreshAfter: {{ .Values.vaultRefreshAfter }}
  destination:
    name: demo-pull-secret
    create: true
    type: kubernetes.io/dockerconfigjson
    # type: Opaque
    transformation:
      excludeRaw: true
      excludes:
      - .*
      templates: 
        .dockerconfigjson:
          text: |
            {{`{
              {{- $username := get .Secret.username -}}
              {{- $password := get .Secret.password -}}
              "auths": {
                "{{ .Secret.registry }}": {
                  "username": "{{ $username }}",
                  "password" "{{ $password }}",
                  "auth": "{{ printf "%s:%s" $username $password | b64enc }}"
                }
              }
            }`}}