apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-secrets
spec:
  vaultAuthRef: {{ .Values.vaultAuthRef }}
  mount: orgprch-projetdemo
  path: db/
  type: kv-v2
  refreshAfter: 1m
  destination:
    name: db-secrets
    create: true