apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-secrets
spec:
  vaultAuthRef: {{ .Values.vaultAuthRef }}
  mount: {{ .Values.vaultSecretMount }}
  path: {{ .Values.vaultSecretPath }}
  type: kv-v2
  refreshAfter: 1m
  destination:
    name: db-secrets
    create: true